[package]
name = "thermorawfilereader"

version = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}

description = "A (relatively) high level interface to Thermo Fisher's RawFileReader library"

documentation = "https://docs.rs/thermorawfilereader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name="fficheck"
path="src/bin.rs"

[[example]]
name = "with_threads"

[features]

default = ["nethost-download", "net8_0"]

nethost-download = ["dotnetrawfilereader-sys/nethost-download"]
doc-only = ["dotnetrawfilereader-sys/doc-only"]
net8_0 = ["netcorehost/net8_0", "dotnetrawfilereader-sys/net8_0"]
netcorehost-latest = ["netcorehost/latest", "dotnetrawfilereader-sys/netcorehost-latest"]


[dependencies]
flatbuffers = "25.2.10"
netcorehost = { workspace = true }

dotnetrawfilereader-sys = { workspace = true, default-features = false}
bytemuck = "1.18.0"

[dev-dependencies]
rayon = { version = "1.9.0" }

[package.metadata.docs.rs]
no-default-features = true
features = ["doc-only"]
