[profile.release]
debug = true

[workspace]

resolver = "2"

members = ["thermorawfilereader", "dotnetrawfilereader-sys", ]

[workspace.package]
version = "0.8.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/mobiusklein/thermorawfilereader.rs.git"

[workspace.dependencies]
thiserror = "1.0.63"
netcorehost = { version = "0.18.0", default-features = false, features = [
    "nethost"
]}

dotnetrawfilereader-sys = { version = "0.8.0", path="./dotnetrawfilereader-sys", default-features = false}
thermorawfilereader = { version = "0.8.0", path = "./thermorawfilereader" }