use crate::gen::schema_generated::librawfilereader::TraceTypeT;

/// This enum mirrors the different types of traces covered in Thermo's RawFileReader library.
///
/// Not all variants are supported by *this* library.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i16)]
pub enum TraceType {
    StartMSChromatogramTraces = -1,
    MassRange = 0,
    TIC = 1,
    BasePeak = 2,
    Fragment = 3,
    Custom = 4,
    PrecursorMass = 5,
    EndMSChromatogramTraces = 6,
    StartAnalogChromatogramTraces = 10,
    Analog1 = 11,
    Analog2 = 12,
    Analog3 = 13,
    Analog4 = 14,
    Analog5 = 15,
    Analog6 = 16,
    Analog7 = 17,
    Analog8 = 18,
    EndAnalogChromatogramTraces = 19,
    StartPDAChromatogramTraces = 20,
    WavelengthRange = 21,
    TotalAbsorbance = 22,
    SpectrumMax = 23,
    EndPDAChromatogramTraces = 24,
    StartUVChromatogramTraces = 30,
    ChannelA = 31,
    ChannelB = 32,
    ChannelC = 33,
    ChannelD = 34,
    ChannelE = 35,
    ChannelF = 36,
    ChannelG = 37,
    ChannelH = 38,
    EndUVChromatogramTraces = 39,
    StartPCA2DChromatogramTraces = 40,
    A2DChannel1 = 41,
    A2DChannel2 = 42,
    A2DChannel3 = 43,
    A2DChannel4 = 44,
    A2DChannel5 = 45,
    A2DChannel6 = 46,
    A2DChannel7 = 47,
    A2DChannel8 = 48,
    EndPCA2DChromatogramTraces = 49,
    EndAllChromatogramTraces = 50
}

impl From<TraceTypeT> for TraceType {
    fn from(value: TraceTypeT) -> Self {
        match value.0 {
            -1 => Self::StartMSChromatogramTraces,
            0 => Self::MassRange,
            1 => Self::TIC,
            2 => Self::BasePeak,
            3 => Self::Fragment,
            4 => Self::Custom,
            5 => Self::PrecursorMass,
            6 => Self::EndMSChromatogramTraces,
            10 => Self::StartAnalogChromatogramTraces,
            11 => Self::Analog1,
            12 => Self::Analog2,
            13 => Self::Analog3,
            14 => Self::Analog4,
            15 => Self::Analog5,
            16 => Self::Analog6,
            17 => Self::Analog7,
            18 => Self::Analog8,
            19 => Self::EndAnalogChromatogramTraces,
            20 => Self::StartPDAChromatogramTraces,
            21 => Self::WavelengthRange,
            22 => Self::TotalAbsorbance,
            23 => Self::SpectrumMax,
            24 => Self::EndPDAChromatogramTraces,
            30 => Self::StartUVChromatogramTraces,
            31 => Self::ChannelA,
            32 => Self::ChannelB,
            33 => Self::ChannelC,
            34 => Self::ChannelD,
            35 => Self::ChannelE,
            36 => Self::ChannelF,
            37 => Self::ChannelG,
            38 => Self::ChannelH,
            39 => Self::EndUVChromatogramTraces,
            40 => Self::StartPCA2DChromatogramTraces,
            41 => Self::A2DChannel1,
            42 => Self::A2DChannel2,
            43 => Self::A2DChannel3,
            44 => Self::A2DChannel4,
            45 => Self::A2DChannel5,
            46 => Self::A2DChannel6,
            47 => Self::A2DChannel7,
            48 => Self::A2DChannel8,
            49 => Self::EndPCA2DChromatogramTraces,
            50 => Self::EndAllChromatogramTraces,
            _ => panic!("Failed to map {:?} to a valid TraceType", value)
        }
    }
}