on: [push, pull_request]

env:
  RUST_BACKTRACE: full
  RUST_LOG: debug
  CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG: true

name: Test (Isolated)
jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Test Suite
    runs-on: ${{ matrix.os }}
    container:
        image: rust:1.76.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
